[package]
name = "serpent_control"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
env_logger = "0.10"

eframe = "0.24"
egui_extras = "0.24"
egui_tiles = "0.4"
rfd = "0.12"

serpent_control_backend = { path = "../control_backend" }
