[package]
name = "serpent_payload"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
env_logger = "0.10"

eframe = "0.24"

windows = { version = "0.52", features = [
    "Win32_System_LibraryLoader",
    "Win32_System_SystemServices",
] }

[lib]
crate-type = ["cdylib"]
